name: build 
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@v1.3.0
        id: scan
        with:
          image: fusionauth/fusionauth-app:latest
          format: yaml
          output: alpine.yaml
      - name: print output
        run: |
          cat ${{ steps.scan.outputs.file }} 
        shell: bash
